### ISSUE TITLE
Expand on configuration over the network

### ISSUE THREAD

**Issue by arichiardi** [tjim/lockstep#1]
From what I undestand the configuration in the README can be used over TCP as well, have you ever tried that?

Can you post an example please?

**Comment by tjim** [comment]
Sorry, I don't understand your question. The README does not mention TCP or any other network protocol. Can you say more?

**Comment by arichiardi** [comment]
Oh sorry,so the question would be, is it possible to connect the client to a over-tcp server taking advantage of emacsserver's [TCP capabilities](http://stackoverflow.com/a/2232128/1888507)?

**Comment by tjim** [comment]
I gave it a try and it looks like if you are using a TCP server, lockstep works as expected.
I've never used a TCP server before and I have to say it's not so easy. If you need help setting that up I think you should look elsewhere.
However once you have it going lockstep should work.

**Comment by arichiardi** [comment]
Can you suggest a configuration/resource? Is the one I linked good enough?

**Comment by tjim** [comment]
Sorry, I don't use this feature of Emacs so I don't know. It seems to be primarily for Windows, I'd do a search based on that.

**Comment by arichiardi** [comment]
> I gave it a try and it looks like if you are using a TCP server, lockstep works as expected.

I just so your comment above and thought you had it working, thank you anyways!
